_wandb:
    value:
        cli_version: 0.23.1
        e:
            u0tcwlqsr14zn3gc59fkzatb6789kh5u:
                codePath: legged_gym/legged_gym/scripts/train.py
                codePathLocal: legged_gym/legged_gym/scripts/train.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1006450962432"
                        used: "610122231808"
                email: runchiuyang@gmail.com
                executable: /home/barry/anaconda3/envs/vl_a01b/bin/python
                git:
                    commit: ef289acaa62795009363b7b819c9186690630441
                    remote: https://github.com/OpenRobotLab/HIMLoco.git
                gpu: NVIDIA GeForce RTX 4070 Ti SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 8448
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4070 Ti SUPER
                      uuid: GPU-5a5964d7-7cb3-36d9-33e7-dc9937aba47a
                host: barry-System-Product-Name
                memory:
                    total: "33451171840"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.17
                program: /home/barry/VisualLOCO_linxai/VL_a01b/visualLoco_a01b/legged_gym/legged_gym/scripts/train.py
                python: CPython 3.8.20
                root: /home/barry/VisualLOCO_linxai/VL_a01b/visualLoco_a01b
                startedAt: "2025-12-31T14:08:45.047950Z"
                writerId: u0tcwlqsr14zn3gc59fkzatb6789kh5u
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
            "4": 3.8.20
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
algorithm:
    value:
        clip_param: 0.2
        desired_kl: 0.01
        entropy_coef: 0.01
        gamma: 0.99
        lam: 0.95
        learning_rate: 0.001
        max_grad_norm: 1
        num_learning_epochs: 5
        num_mini_batches: 4
        schedule: adaptive
        use_clipped_value_loss: true
        value_loss_coef: 1
asset:
    value:
        angular_damping: 0
        armature: 0
        collapse_fixed_joints: true
        default_dof_drive_mode: 3
        density: 0.001
        disable_gravity: false
        file: '{LEGGED_GYM_ROOT_DIR}/resources/robots/A01b/urdf/A01b.urdf'
        fix_base_link: false
        flip_visual_attachments: true
        foot_name: foot
        linear_damping: 0
        max_angular_velocity: 1000
        max_linear_velocity: 1000
        name: aliengo
        penalize_contacts_on:
            - thigh
            - calf
            - base
        privileged_contacts_on:
            - base
            - thigh
            - calf
        replace_cylinder_with_capsule: false
        self_collisions: 1
        terminate_after_contacts_on:
            - base
        thickness: 0.01
commands:
    value:
        curriculum: true
        heading_command: true
        max_curriculum: 2
        num_commands: 4
        ranges:
            ang_vel_yaw:
                - -3.14
                - 3.14
            heading:
                - -3.14
                - 3.14
            lin_vel_x:
                - -1
                - 1
            lin_vel_y:
                - -1
                - 1
        resampling_time: 10
control:
    value:
        action_scale: 0.25
        control_type: P
        damping:
            joint: 7
        decimation: 10
        hip_reduction: 1
        stiffness:
            joint: 300
domain_rand:
    value:
        com_displacement_range:
            - -0.05
            - 0.05
        delay: true
        disturbance: true
        disturbance_interval: 8
        disturbance_range:
            - -30
            - 30
        friction_range:
            - 0.2
            - 1.25
        initial_joint_pos_range:
            - 0.5
            - 1.5
        kd_range:
            - 0.9
            - 1.1
        kp_range:
            - 0.9
            - 1.1
        link_mass_range:
            - 0.9
            - 1.1
        max_push_vel_xy: 1
        motor_strength_range:
            - 0.9
            - 1.1
        payload_mass_range:
            - -1
            - 2
        push_interval: 800
        push_interval_s: 16
        push_robots: true
        randomize_com_displacement: true
        randomize_friction: true
        randomize_initial_joint_pos: true
        randomize_kd: true
        randomize_kp: true
        randomize_link_mass: false
        randomize_motor_strength: true
        randomize_payload_mass: true
        randomize_restitution: false
        restitution_range:
            - 0
            - 1
env:
    value:
        env_spacing: 3
        episode_length_s: 20
        height_map_real_H: 11
        height_map_shape:
            - 1
            - 19
            - 11
        num_actions: 12
        num_additional_obs: 6
        num_envs: 4096
        num_height_map_scans: 209
        num_observations: 270
        num_one_step_observations: 45
        num_one_step_privileged_obs: 260
        num_privileged_obs: 260
        send_timeouts: true
init_state:
    value:
        ang_vel:
            - 0
            - 0
            - 0
        default_joint_angles:
            FL_calf_joint: 1.44
            FL_hip_joint: -0.049
            FL_thigh_joint: -0.81
            FR_calf_joint: 1.44
            FR_hip_joint: 0.049
            FR_thigh_joint: -0.81
            RL_calf_joint: 1.44
            RL_hip_joint: -0.049
            RL_thigh_joint: -0.81
            RR_calf_joint: 1.44
            RR_hip_joint: 0.049
            RR_thigh_joint: -0.81
        lin_vel:
            - 0
            - 0
            - 0
        pos:
            - 0
            - 0
            - 0.6
        rot:
            - 0
            - 0
            - 0
            - 1
noise:
    value:
        add_noise: true
        noise_level: 1
        noise_scales:
            ang_vel: 0.2
            dof_pos: 0.01
            dof_vel: 1.5
            gravity: 0.05
            height_measurements: 0.1
            lin_vel: 0.1
normalization:
    value:
        clip_actions: 100
        clip_observations: 100
        obs_scales:
            ang_vel: 0.25
            dof_pos: 1
            dof_vel: 0.05
            height_measurements: 5
            lin_vel: 2
policy:
    value:
        activation: elu
        actor_hidden_dims:
            - 512
            - 256
            - 128
        critic_hidden_dims:
            - 512
            - 256
            - 128
        init_noise_std: 1
        self_attn: false
        vel_est: true
rewards:
    value:
        base_height_target: 0.61
        clearance_height_target: -0.48
        max_contact_force: 100
        only_positive_rewards: false
        scales:
            action_rate: -0.01
            ang_vel_xy: -0.05
            base_height: -10
            collision: -0.08
            contact_center: -0.1
            delta_torques: -1e-07
            dof_acc: -2.5e-07
            dof_error: -0.08
            dof_pos_limits: 0
            dof_vel: -0
            dof_vel_limits: 0
            feet_air_time: 0
            feet_contact_forces: -0
            feet_slip: -0.08
            feet_stumble: -0
            foot_clearance: -0.01
            hip_pos: -1.5
            joint_power: -7e-06
            lin_vel_z: -2
            orientation: -0.2
            smoothness: -0.01
            stand_contact: -1
            stand_still: -0.8
            stand_yawvel: -0.5
            termination: -0
            torque_limits: 0
            torques: -0
            tracking_ang_vel: 0.5
            tracking_lin_vel: 1
        soft_dof_pos_limit: 0.95
        soft_dof_vel_limit: 0.95
        soft_torque_limit: 0.95
        tracking_sigma: 0.25
runner:
    value:
        algorithm_class_name: HIMPPO
        checkpoint: -1
        experiment_name: rough_A01b
        load_run: -1
        max_iterations: 200000
        num_steps_per_env: 100
        policy_class_name: AttnActorCritic
        project_name: VisualLoco_a01b
        resume: false
        resume_path: null
        run_name: ""
        save_interval: 20
runner_class_name:
    value: HIMOnPolicyRunner
seed:
    value: 1
sim:
    value:
        dt: 0.002
        gravity:
            - 0
            - 0
            - -9.81
        physx:
            bounce_threshold_velocity: 0.5
            contact_collection: 2
            contact_offset: 0.01
            default_buffer_size_multiplier: 5
            max_depenetration_velocity: 1
            max_gpu_contact_pairs: 8388608
            num_position_iterations: 4
            num_threads: 10
            num_velocity_iterations: 0
            rest_offset: 0
            solver_type: 1
        substeps: 1
        up_axis: 1
terrain:
    value:
        border_size: 25
        curriculum: true
        dynamic_friction: 1
        horizontal_scale: 0.1
        max_init_terrain_level: 5
        measure_heights: true
        measured_points_x:
            - -0.8
            - -0.7
            - -0.6
            - -0.5
            - -0.4
            - -0.3
            - -0.2
            - -0.1
            - 0
            - 0.1
            - 0.2
            - 0.3
            - 0.4
            - 0.5
            - 0.6
            - 0.7
            - 0.8
            - 0.9
            - 1
        measured_points_y:
            - -0.5
            - -0.4
            - -0.3
            - -0.2
            - -0.1
            - 0
            - 0.1
            - 0.2
            - 0.3
            - 0.4
            - 0.5
        mesh_type: trimesh
        num_cols: 20
        num_rows: 10
        num_sub_terrains: 200
        restitution: 0
        selected: false
        slope_treshold: 0.75
        static_friction: 1
        terrain_kwargs: null
        terrain_length: 8
        terrain_proportions:
            - 0.1
            - 0.2
            - 0.3
            - 0.3
            - 0.1
        terrain_width: 8
        vertical_scale: 0.005
viewer:
    value:
        lookat:
            - 11
            - 5
            - 3
        pos:
            - 10
            - 0
            - 6
        ref_env: 0
